version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean build
      - echo "Java build completed"

artifacts:
  files:
    - build/libs/*.jar