version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - chmod +x ./gradlew
      - sed -i 's/\r$//' gradlew
  build:
    commands:
      - ./gradlew clean
      - ./gradlew build
      - echo "Java build completed"

artifacts:
  files:
    - build/libs/*.jar